package io.sdb.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("campaign", "id", Campaign.class);
		arp.addMapping("cart", "id", Cart.class);
		arp.addMapping("delivery_corp", "code", DeliveryCorp.class);
		// Composite Primary Key order: favorite_goods,favorite_user
		arp.addMapping("favorite_goods", "favorite_goods,favorite_user", FavoriteGoods.class);
		arp.addMapping("goods", "sn", Goods.class);
		arp.addMapping("logistics", "tracking_no", Logistics.class);
		arp.addMapping("order_detail", "detail_id", OrderDetail.class);
		arp.addMapping("order_master", "order_id", OrderMaster.class);
		arp.addMapping("product", "sn", Product.class);
		arp.addMapping("product_category", "id", ProductCategory.class);
		arp.addMapping("receiver", "id", Receiver.class);
		arp.addMapping("schedule_job", "job_id", ScheduleJob.class);
		arp.addMapping("schedule_job_log", "log_id", ScheduleJobLog.class);
		arp.addMapping("sn", "type", Sn.class);
		arp.addMapping("specification", "id", Specification.class);
		arp.addMapping("sys_captcha", "uuid", SysCaptcha.class);
		arp.addMapping("sys_config", "id", SysConfig.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_menu", "menu_id", SysMenu.class);
		arp.addMapping("sys_oss", "id", SysOss.class);
		arp.addMapping("sys_role", "role_id", SysRole.class);
		arp.addMapping("sys_role_menu", "id", SysRoleMenu.class);
		arp.addMapping("sys_user", "user_id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("sys_user_token", "user_id", SysUserToken.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

