package io.sdb.model;

import io.sdb.model.base.BaseCampaign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Campaign extends BaseCampaign<Campaign> {
	public static final Campaign dao = new Campaign().dao();
}
