package io.sdb.model;

import io.sdb.model.base.BaseDeliveryCorp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryCorp extends BaseDeliveryCorp<DeliveryCorp> {
	public static final DeliveryCorp dao = new DeliveryCorp().dao();
}
