package io.sdb.model;

import io.sdb.model.base.BaseFavoriteGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FavoriteGoods extends BaseFavoriteGoods<FavoriteGoods> {
	public static final FavoriteGoods dao = new FavoriteGoods().dao();
}
