package io.sdb.model;

import io.sdb.model.base.BaseArea;
import io.sdb.model.base.BaseGoods;
import lombok.Data;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods().dao();

	private List<Product> productList;
}
