package io.sdb.model;

import io.sdb.model.base.BaseGroupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Groupon extends BaseGroupon<Groupon> {
	public static final Groupon dao = new Groupon().dao();
}
