package io.sdb.model;

import io.sdb.model.base.BaseGrouponTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GrouponTeam extends BaseGrouponTeam<GrouponTeam> {
	public static final GrouponTeam dao = new GrouponTeam().dao();
}
