package io.sdb.model;

import io.sdb.model.base.BaseLogistics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logistics extends BaseLogistics<Logistics> {
	public static final Logistics dao = new Logistics().dao();
}
