package io.sdb.model;

import io.sdb.model.base.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	public static final OrderDetail dao = new OrderDetail().dao();
}
