package io.sdb.model;

import io.sdb.model.base.BaseOrderMaster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderMaster extends BaseOrderMaster<OrderMaster> {
	public static final OrderMaster dao = new OrderMaster().dao();
}
