package io.sdb.model;

import io.sdb.model.base.BaseProduct;
import lombok.Data;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product().dao();

	Integer quantity;
}
