package io.sdb.model;

import io.sdb.model.base.BaseProductCategory;
import lombok.Data;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	public static final ProductCategory dao = new ProductCategory().dao();

	String parentName;
	boolean open;
}
