package io.sdb.model;

import io.sdb.model.base.BaseReceiver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Receiver extends BaseReceiver<Receiver> {
	public static final Receiver dao = new Receiver().dao();
}
