package io.sdb.model;

import io.sdb.model.base.BaseScheduleJobLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScheduleJobLog extends BaseScheduleJobLog<ScheduleJobLog> {
	public static final ScheduleJobLog dao = new ScheduleJobLog().dao();
}
