package io.sdb.model;

import io.sdb.model.base.BaseSn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sn extends BaseSn<Sn> {
	public static final Sn dao = new Sn().dao();
}
