package io.sdb.model;

import io.sdb.model.base.BaseSysCaptcha;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCaptcha extends BaseSysCaptcha<SysCaptcha> {
	public static final SysCaptcha dao = new SysCaptcha().dao();
}
