package io.sdb.model;

import io.sdb.model.base.BaseSysOss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOss extends BaseSysOss<SysOss> {
	public static final SysOss dao = new SysOss().dao();
}
