package io.sdb.model;

import io.sdb.model.base.BaseSysRole;
import lombok.Data;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();

	private List<Long> menuIdList;
}
