package io.sdb.model;

import io.sdb.model.base.BaseSysUserToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserToken extends BaseSysUserToken<SysUserToken> {
	public static final SysUserToken dao = new SysUserToken().dao();
}
