package io.sdb.model;

import io.sdb.model.base.BaseTbUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUser extends BaseTbUser<TbUser> {
	public static final TbUser dao = new TbUser().dao();
}
