package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setCaption(java.lang.String caption) {
		set("caption", caption);
	}
	
	public java.lang.String getCaption() {
		return getStr("caption");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setIsDelivery(java.lang.Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}
	
	public java.lang.Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setIsMarketable(java.lang.Boolean isMarketable) {
		set("is_marketable", isMarketable);
	}
	
	public java.lang.Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public void setParameterValues(java.lang.String parameterValues) {
		set("parameter_values", parameterValues);
	}
	
	public java.lang.String getParameterValues() {
		return getStr("parameter_values");
	}

	public void setSpecificationItems(java.lang.String specificationItems) {
		set("specification_items", specificationItems);
	}
	
	public java.lang.String getSpecificationItems() {
		return getStr("specification_items");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public void setProductImages(java.lang.String productImages) {
		set("product_images", productImages);
	}
	
	public java.lang.String getProductImages() {
		return getStr("product_images");
	}

	public void setWeight(java.lang.Float weight) {
		set("weight", weight);
	}
	
	public java.lang.Float getWeight() {
		return getFloat("weight");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}
	
	public java.lang.Long getProductCategoryId() {
		return getLong("product_category_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
