package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysConfig<M extends BaseSysConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setParamKey(java.lang.String paramKey) {
		set("param_key", paramKey);
	}
	
	public java.lang.String getParamKey() {
		return getStr("param_key");
	}

	public void setParamValue(java.lang.String paramValue) {
		set("param_value", paramValue);
	}
	
	public java.lang.String getParamValue() {
		return getStr("param_value");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
