package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFavoriteGoods<M extends BaseFavoriteGoods<M>> extends Model<M> implements IBean {

	public void setFavoriteUser(java.lang.String favoriteUser) {
		set("favorite_user", favoriteUser);
	}
	
	public java.lang.String getFavoriteUser() {
		return getStr("favorite_user");
	}

	public void setFavoriteGoods(java.lang.String favoriteGoods) {
		set("favorite_goods", favoriteGoods);
	}
	
	public java.lang.String getFavoriteGoods() {
		return getStr("favorite_goods");
	}

}
