package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderDetail<M extends BaseOrderDetail<M>> extends Model<M> implements IBean {

	public void setDetailId(java.lang.String detailId) {
		set("detail_id", detailId);
	}
	
	public java.lang.String getDetailId() {
		return getStr("detail_id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setProductId(java.lang.String productId) {
		set("product_id", productId);
	}
	
	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public void setProductModel(java.lang.String productModel) {
		set("product_model", productModel);
	}
	
	public java.lang.String getProductModel() {
		return getStr("product_model");
	}

	public void setProductSpec(java.lang.String productSpec) {
		set("product_spec", productSpec);
	}
	
	public java.lang.String getProductSpec() {
		return getStr("product_spec");
	}

	public void setProductPrice(java.math.BigDecimal productPrice) {
		set("product_price", productPrice);
	}
	
	public java.math.BigDecimal getProductPrice() {
		return get("product_price");
	}

	public void setProductQuantity(java.lang.Integer productQuantity) {
		set("product_quantity", productQuantity);
	}
	
	public java.lang.Integer getProductQuantity() {
		return getInt("product_quantity");
	}

	public void setProductIcon(java.lang.String productIcon) {
		set("product_icon", productIcon);
	}
	
	public java.lang.String getProductIcon() {
		return getStr("product_icon");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
