package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderMaster<M extends BaseOrderMaster<M>> extends Model<M> implements IBean {

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setBuyerName(java.lang.String buyerName) {
		set("buyer_name", buyerName);
	}
	
	public java.lang.String getBuyerName() {
		return getStr("buyer_name");
	}

	public void setBuyerPhone(java.lang.String buyerPhone) {
		set("buyer_phone", buyerPhone);
	}
	
	public java.lang.String getBuyerPhone() {
		return getStr("buyer_phone");
	}

	public void setBuyerAddress(java.lang.String buyerAddress) {
		set("buyer_address", buyerAddress);
	}
	
	public java.lang.String getBuyerAddress() {
		return getStr("buyer_address");
	}

	public void setBuyerId(java.lang.String buyerId) {
		set("buyer_id", buyerId);
	}
	
	public java.lang.String getBuyerId() {
		return getStr("buyer_id");
	}

	public void setNeedInvoice(java.lang.Integer needInvoice) {
		set("need_invoice", needInvoice);
	}
	
	public java.lang.Integer getNeedInvoice() {
		return getInt("need_invoice");
	}

	public void setInvoiceType(java.lang.Integer invoiceType) {
		set("invoice_type", invoiceType);
	}
	
	public java.lang.Integer getInvoiceType() {
		return getInt("invoice_type");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTaxNumber(java.lang.String taxNumber) {
		set("tax_number", taxNumber);
	}
	
	public java.lang.String getTaxNumber() {
		return getStr("tax_number");
	}

	public void setCompanyAddress(java.lang.String companyAddress) {
		set("company_address", companyAddress);
	}
	
	public java.lang.String getCompanyAddress() {
		return getStr("company_address");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
	}
	
	public java.lang.String getBankAccount() {
		return getStr("bank_account");
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
	}
	
	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public void setTrackingNumber(java.lang.String trackingNumber) {
		set("tracking_number", trackingNumber);
	}
	
	public java.lang.String getTrackingNumber() {
		return getStr("tracking_number");
	}

	public void setDeliveryCode(java.lang.String deliveryCode) {
		set("delivery_code", deliveryCode);
	}
	
	public java.lang.String getDeliveryCode() {
		return getStr("delivery_code");
	}

	public void setRefundTradeNo(java.lang.String refundTradeNo) {
		set("refund_trade_no", refundTradeNo);
	}
	
	public java.lang.String getRefundTradeNo() {
		return getStr("refund_trade_no");
	}

	public void setPayTradeNo(java.lang.String payTradeNo) {
		set("pay_trade_no", payTradeNo);
	}
	
	public java.lang.String getPayTradeNo() {
		return getStr("pay_trade_no");
	}

	public void setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
	}
	
	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setContract(java.lang.String contract) {
		set("contract", contract);
	}
	
	public java.lang.String getContract() {
		return getStr("contract");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
