package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
	}
	
	public java.lang.Long getMenuId() {
		return getLong("menu_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setPerms(java.lang.String perms) {
		set("perms", perms);
	}
	
	public java.lang.String getPerms() {
		return getStr("perms");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

}
