package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setMaOpenId(java.lang.String maOpenId) {
		set("ma_open_id", maOpenId);
	}
	
	public java.lang.String getMaOpenId() {
		return getStr("ma_open_id");
	}

	public void setUnionId(java.lang.String unionId) {
		set("union_id", unionId);
	}
	
	public java.lang.String getUnionId() {
		return getStr("union_id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public void setAreaId(java.lang.Integer areaId) {
		set("area_id", areaId);
	}
	
	public java.lang.Integer getAreaId() {
		return getInt("area_id");
	}

	public void setLanguage(java.lang.Integer language) {
		set("language", language);
	}
	
	public java.lang.Integer getLanguage() {
		return getInt("language");
	}

	public void setVolunteer(java.lang.Integer volunteer) {
		set("volunteer", volunteer);
	}
	
	public java.lang.Integer getVolunteer() {
		return getInt("volunteer");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
