package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScheduleJobLog<M extends BaseScheduleJobLog<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}
	
	public java.lang.Long getLogId() {
		return getLong("log_id");
	}

	public void setJobId(java.lang.Long jobId) {
		set("job_id", jobId);
	}
	
	public java.lang.Long getJobId() {
		return getLong("job_id");
	}

	public void setBeanName(java.lang.String beanName) {
		set("bean_name", beanName);
	}
	
	public java.lang.String getBeanName() {
		return getStr("bean_name");
	}

	public void setMethodName(java.lang.String methodName) {
		set("method_name", methodName);
	}
	
	public java.lang.String getMethodName() {
		return getStr("method_name");
	}

	public void setParams(java.lang.String params) {
		set("params", params);
	}
	
	public java.lang.String getParams() {
		return getStr("params");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setError(java.lang.String error) {
		set("error", error);
	}
	
	public java.lang.String getError() {
		return getStr("error");
	}

	public void setTimes(java.lang.Integer times) {
		set("times", times);
	}
	
	public java.lang.Integer getTimes() {
		return getInt("times");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
