package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrouponTeam<M extends BaseGrouponTeam<M>> extends Model<M> implements IBean {

	public void setGrouponId(java.lang.String grouponId) {
		set("groupon_id", grouponId);
	}
	
	public java.lang.String getGrouponId() {
		return getStr("groupon_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setCaptain(java.lang.Integer captain) {
		set("captain", captain);
	}
	
	public java.lang.Integer getCaptain() {
		return getInt("captain");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
