package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReceiver<M extends BaseReceiver<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}
	
	public java.lang.String getAreaName() {
		return getStr("area_name");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}
	
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public void setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
	}
	
	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}
	
	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}
	
	public java.lang.Long getAreaId() {
		return getLong("area_id");
	}

	public void setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
	}
	
	public java.lang.String getMemberId() {
		return getStr("member_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
