package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
	}
	
	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public void setSpecificationValues(java.lang.String specificationValues) {
		set("specification_values", specificationValues);
	}
	
	public java.lang.String getSpecificationValues() {
		return getStr("specification_values");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	public void setGoodsSn(java.lang.String goodsSn) {
		set("goods_sn", goodsSn);
	}
	
	public java.lang.String getGoodsSn() {
		return getStr("goods_sn");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
