package io.sdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCampaign<M extends BaseCampaign<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setParamName1(java.lang.String paramName1) {
		set("param_name1", paramName1);
	}
	
	public java.lang.String getParamName1() {
		return getStr("param_name1");
	}

	public void setParamValue1(java.lang.String paramValue1) {
		set("param_value1", paramValue1);
	}
	
	public java.lang.String getParamValue1() {
		return getStr("param_value1");
	}

	public void setParamName2(java.lang.String paramName2) {
		set("param_name2", paramName2);
	}
	
	public java.lang.String getParamName2() {
		return getStr("param_name2");
	}

	public void setParamValue2(java.lang.String paramValue2) {
		set("param_value2", paramValue2);
	}
	
	public java.lang.String getParamValue2() {
		return getStr("param_value2");
	}

	public void setParamName3(java.lang.String paramName3) {
		set("param_name3", paramName3);
	}
	
	public java.lang.String getParamName3() {
		return getStr("param_name3");
	}

	public void setParamValue3(java.lang.String paramValue3) {
		set("param_value3", paramValue3);
	}
	
	public java.lang.String getParamValue3() {
		return getStr("param_value3");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
